---
title: "ESM 204 HW 4: Calculating the SCC and Policy Choice under Uncertainty"
author: "Kort Alexander, Eva Wilson, Julia Wilson"
date: "5/19/2022"
output: 
  html_document:
    theme: spacelab
    code_folding: hide
---

```{r setup, include = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
library(here)
```

```{r}
damages <- read_csv(here("damages.csv"))
warming <- read_csv(here("warming.csv"))
```

### 1. Estimate a quadratic damage function 

```{r}
damages <- damages %>% 
  mutate(warming_sq = warming^2)
damages_model <- lm(data = damages, damages ~ 0 + warming + warming_sq)

warming_range <- damages$warming
damage_predict <- predict(damages_model, list(warming = warming_range, warming_sq = warming_range^2))
damage_predictions <- tibble(warming_range, damage_predict)

ggplot() +
  geom_point(data = damages, aes(x = warming, y = damages)) +
  geom_line(data = damage_predictions, aes(x = warming_range, y = damage_predict), color = "blue") +
  labs(x = "Warming (degrees C)", y = "Damages ($)", title = "Estimated damages (USD) per unit of additional warming (Celsius)") +
  theme(plot.title = element_text(hjust = 0.5, face = "bold")) +
  theme(axis.title = element_text(face = "bold")) +
  theme(strip.background = element_rect(color= "white", fill = "gray"))
```

***

### 2. Predict damages under the baseline climate and the pulse scenario

```{r}
damage_function <- function(warming) {
  damages <- damages_model$coefficients[1] * warming + damages_model$coefficients[2] * (warming^2)
  return(damages)
}
```

```{r}
warming <- warming %>% 
  mutate(damages_baseline = damage_function(warming_baseline), damages_pulse = damage_function(warming_pulse)) %>% 
  mutate(difference = damage_function(warming_pulse) - damage_function(warming_baseline)) %>% 
  mutate(difference_per_ton = (damage_function(warming_pulse) - damage_function(warming_baseline)) / 35000000000 )

ggplot(warming, aes(x = year, y = damages_baseline)) +
  geom_line(size = 1) +
  labs(x = "Year", y = "Damages ($)", title = "Baseline damages ($)") +
  theme_minimal(14) +
  theme(plot.title = element_text(hjust = 0.5, face = "bold")) +
  theme(axis.title = element_text(face = "bold")) +
  theme(strip.background = element_rect(color= "white", fill = "gray"))

ggplot(warming, aes(x = year, y = damages_pulse)) +
  geom_line(size = 1) +
  labs(x = "Year", y = "Damages ($)", title = "Damages ($) with pulse") +
  theme_minimal(14) +
  theme(plot.title = element_text(hjust = 0.5, face = "bold")) +
  theme(axis.title = element_text(face = "bold")) +
  theme(strip.background = element_rect(color= "white", fill = "gray"))

ggplot(warming, aes(x = year, y = difference)) +
  geom_line(size = 1) +
  labs(x = "Year", y = "Damages ($)", title = "Difference in damages ($) with pulse") +
  theme_minimal(14) +
  theme(plot.title = element_text(hjust = 0.5, face = "bold")) +
  theme(axis.title = element_text(face = "bold")) +
  theme(strip.background = element_rect(color= "white", fill = "gray"))

ggplot(warming, aes(x = year, y = difference_per_ton)) +
  geom_line(size = 1) +
  labs(x = "Year", y = "Damages ($/tonCO2)", title = "Difference in damages with pulse per ton of CO2") +
  theme_minimal(14) +
  theme(plot.title = element_text(hjust = 0.5, face = "bold")) +
  theme(axis.title = element_text(face = "bold")) +
  theme(strip.background = element_rect(color= "white", fill = "gray"))
```

***

### 3. Plot the SCC against reasonable discount rates

```{r}
SCC_function <- function(r){
  sum <- 0
  for(i in seq(1, 79, 1)){
    sum <- sum + (warming[i, 8] / (1 + r)^i)
  }
  return(sum)
}

discount_rate <- seq(0, 0.1, 0.0025)
SCC <- map(discount_rate, SCC_function) %>% unlist()
SCC_table <- tibble(discount_rate, SCC)

ggplot(SCC_table, aes(x = discount_rate * 100, y = SCC)) +
  geom_line(size = 1) +
  labs(x = "Discount rate (%)", y = "SCC ($/ton)", title = "Social cost of carbon per discount rate") +
  theme_minimal(14) + 
  theme(axis.title = element_text(face = "bold")) +
  theme(strip.background = element_rect(color= "white", fill = "gray")) +
  theme(plot.title = element_text(hjust = 0.5, face = "bold")) 
```

Higher discount rates result in a lower SCC; if future climate damages are discounted at a high rate, we would be placing less value on avoiding those damages today.

***